# This configuration is for install, build and start commands
# powered by Nixpacks.
# https://nixpacks.com/docs/configuration/file

# Nixpacks can figure the provider out automatically
providers = ["node"]

# NodeJS version -> field "engines": { "node" } in package.json
[variables]
NIXPACKS_NODE_VERSION = '22'

# Start command -> the start script in package.json
# [start]
# cmd = "node .output/server/index.mjs"

# Package manager -> depending on the lockfile detected
