import { defineConfig } from "vite-plus"

const ignorePatterns = [
  "**/.nuxt/**",
  "**/.output/**",
  "**/cache/**",
  "**/dist/**",
  "**/node_modules/**",
  "**/*.min.css",
  "pnpm-lock.yaml",
]

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  run: {
    cache: {
      scripts: true,
    },
  },
  lint: {
    plugins: [
      "eslint",
      "typescript",
      "unicorn",
      "oxc",
      "import",
      "node",
      "promise",
      "vitest",
      "vue",
    ],
    categories: {
      correctness: "error",
      suspicious: "error",
      perf: "error",
    },
    rules: {
      // Pedantic
      eqeqeq: "error",
      "no-throw-literal": "error",
      "no-promise-executor-return": "error",
      "no-self-compare": "error",
      "no-useless-return": "error",
      "no-else-return": "error",
      "no-lonely-if": "error",
      "no-loop-func": "error",
      "array-callback-return": "error",
      radix: "error",
      "symbol-description": "error",
      "unicorn/explicit-length-check": "error",
      "unicorn/new-for-builtins": "error",
      "typescript/ban-ts-comment": "error",
      "typescript/only-throw-error": "error",
      "typescript/prefer-includes": "error",
      "typescript/prefer-promise-reject-errors": "error",
      "typescript/no-misused-promises": "error",
      "typescript/switch-exhaustiveness-check": "error",
      "typescript/prefer-nullish-coalescing": "error",
      "typescript/restrict-plus-operands": "error",
      "typescript/return-await": "error",
      "typescript/no-deprecated": "error",
      "max-lines": ["error", { max: 400, skipBlankLines: true, skipComments: true }],
      "max-lines-per-function": [
        "error",
        { max: 80, skipBlankLines: true, skipComments: true, IIFEs: true },
      ],
      "max-depth": ["error", 4],
      "max-nested-callbacks": ["error", 3],
      "max-classes-per-file": ["error", 1],
      "import/max-dependencies": ["error", { max: 20, ignoreTypeImports: true }],
      // Restriction
      "no-var": "error",
      "no-console": ["error", { allow: ["warn", "error"] }],
      "import/no-cycle": "error",
      "unicorn/prefer-node-protocol": "error",
      "unicorn/prefer-module": "error",
      "typescript/no-explicit-any": "error",
      "typescript/no-non-null-assertion": "error",
      "typescript/no-import-type-side-effects": "error",
      "typescript/no-empty-object-type": "error",
      "vue/no-import-compiler-macros": "error",
      "vue/no-multiple-slot-args": "error",
      complexity: ["error", 15],
      // Style
      "prefer-const": "error",
      "object-shorthand": "error",
      "prefer-template": "error",
      "prefer-object-spread": "error",
      "no-useless-computed-key": "error",
      "no-implicit-coercion": "error",
      "import/no-duplicates": "error",
      "import/first": "error",
      "import/consistent-type-specifier-style": ["error", "prefer-top-level"],
      "max-params": ["error", 4],
      "max-statements": ["error", 25],
      // Nursery
      "typescript/no-unnecessary-condition": "error",
      "typescript/prefer-optional-chain": "error",
    },
    env: {
      browser: true,
      node: true,
      es2024: true,
    },
    ignorePatterns,
    options: {
      typeAware: true,
      typeCheck: true,
    },
  },
  fmt: {
    semi: false,
    ignorePatterns,
  },
})
